services:
  postgres:
    image: postgres:15
    container_name: phonebook_db
    environment:
      POSTGRES_DB: phonebook
      POSTGRES_USER: phonebook_user
      POSTGRES_PASSWORD: phonebook_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U phonebook_user -d phonebook"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: phonebook_backend
    environment:
      PSQL_URL: postgresql://phonebook_user:phonebook_pass@postgres:5432/phonebook
      SECRET_KEY: ${SECRET_KEY:-default-dev-secret-key-change-in-production}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["python", "start_app.py"]

volumes:
  postgres_data: